vcpkg_from_github(
	OUT_SOURCE_PATH SOURCE_PATH
	REPO iswenzz/CGSC
	REF 3ee0b374c260599c0366db3dbfab2e5925ae3e3a
	SHA512 0013502e5f1b84868a086f227701e9531ba6eec1ee06d857093e2b317b7986164807d6ca48ba9aa7104ef70fa9e69bf1a1073096154dbdeba1dbec6897b8111c
	HEAD_REF develop
)

vcpkg_cmake_configure(SOURCE_PATH "${SOURCE_PATH}")
vcpkg_cmake_install()
vcpkg_cmake_config_fixup(CONFIG_PATH "lib/cmake/CGSC")

file(INSTALL "${SOURCE_PATH}/README.md" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/include/CGSC/.github")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/include/CGSC/.vcpkg")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/include/CGSC/cmake")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/include/CGSC/asm")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/include/CGSC/docs")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/include/CGSC/scripts")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/include/CGSC/tests")
