if(VCPKG_TARGET_ARCHITECTURE STREQUAL "x86")
	vcpkg_download_distfile(ARCHIVE
		URLS https://iswenzz.com/static/vcpkg/cef/cef_binary_149.0.6%2Bg0d0eeb6%2Bchromium-149.0.7827.201_windows32.tar.bz2
		FILENAME "cef_windows32.tar.bz2"
		SHA512 07eed6bf944668199595d9072e12abff28dac1e230886d0b2d6bbf009095e55e2231bd45b2fc605422b0d25195a4bc6c7bd30192c1dd7a0fe2e9ad24cc409983
	)
elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
	vcpkg_download_distfile(ARCHIVE
		URLS https://cef-builds.spotifycdn.com/cef_binary_149.0.6%2Bg0d0eeb6%2Bchromium-149.0.7827.201_windows64.tar.bz2
		FILENAME "cef_windows64.tar.bz2"
		SHA512 66200e0050721e2d5df68fcd737daa48080ae616cc063d0cc452d0059ae9e355b5c50182fe532120ba19d92a91559db1a8b68f7ae51d5e281f189474bdf8da52
	)
else()
	message(FATAL_ERROR "CEF does not support architecture: ${VCPKG_TARGET_ARCHITECTURE}")
endif()

vcpkg_extract_source_archive_ex(
	OUT_SOURCE_PATH SOURCE_PATH
	ARCHIVE ${ARCHIVE}
)

set(PREV_VCPKG_LIBRARY_LINKAGE ${VCPKG_LIBRARY_LINKAGE})
set(VCPKG_POLICY_SKIP_ARCHITECTURE_CHECK enabled)
set(VCPKG_POLICY_SKIP_DUMPBIN_CHECKS enabled)
set(VCPKG_LIBRARY_LINKAGE static)

set(CEF_CONFIG_OPTS -DUSE_SANDBOX=NO)
if("${VCPKG_CRT_LINKAGE}" STREQUAL "dynamic")
	list(APPEND CEF_CONFIG_OPTS -DCEF_RUNTIME_LIBRARY_FLAG=/MD)
endif()

file(COPY ${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt DESTINATION ${SOURCE_PATH})

vcpkg_cmake_configure(
	SOURCE_PATH "${SOURCE_PATH}"
	OPTIONS ${CEF_CONFIG_OPTS})

set(VCPKG_LIBRARY_LINKAGE ${PREV_VCPKG_LIBRARY_LINKAGE})

vcpkg_cmake_install()
vcpkg_copy_pdbs()

file(INSTALL "${SOURCE_PATH}/include" DESTINATION "${CURRENT_PACKAGES_DIR}")

file(GLOB DLLS "${SOURCE_PATH}/Release/*.dll")
file(INSTALL ${DLLS} DESTINATION "${CURRENT_PACKAGES_DIR}/bin")
file(GLOB LIBS "${SOURCE_PATH}/Release/*.lib")
file(INSTALL ${LIBS} DESTINATION "${CURRENT_PACKAGES_DIR}/lib")
file(GLOB BIN_FILES "${SOURCE_PATH}/Release/*.bin")
file(INSTALL ${BIN_FILES} DESTINATION "${CURRENT_PACKAGES_DIR}/bin")
file(GLOB JSON_FILES "${SOURCE_PATH}/Release/*.json")
file(INSTALL ${JSON_FILES} DESTINATION "${CURRENT_PACKAGES_DIR}/bin")

if(VCPKG_BUILD_TYPE STREQUAL "debug" OR NOT DEFINED VCPKG_BUILD_TYPE)
	file(GLOB DEBUG_DLLS "${SOURCE_PATH}/Debug/*.dll")
	file(INSTALL ${DEBUG_DLLS} DESTINATION "${CURRENT_PACKAGES_DIR}/debug/bin")
	file(GLOB DEBUG_LIBS "${SOURCE_PATH}/Debug/*.lib")
	file(INSTALL ${DEBUG_LIBS} DESTINATION "${CURRENT_PACKAGES_DIR}/debug/lib")
	file(GLOB DEBUG_BIN_FILES "${SOURCE_PATH}/Debug/*.bin")
	file(INSTALL ${DEBUG_BIN_FILES} DESTINATION "${CURRENT_PACKAGES_DIR}/debug/bin")
	file(GLOB DEBUG_JSON_FILES "${SOURCE_PATH}/Debug/*.json")
	file(INSTALL ${DEBUG_JSON_FILES} DESTINATION "${CURRENT_PACKAGES_DIR}/debug/bin")
endif()

file(INSTALL "${SOURCE_PATH}/Resources" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
file(INSTALL "${SOURCE_PATH}/LICENSE.txt" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
